# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindowGUI.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(405, 442)
        MainWindow.setMouseTracking(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.titleLE = QtWidgets.QLineEdit(self.centralwidget)
        self.titleLE.setObjectName("titleLE")
        self.gridLayout.addWidget(self.titleLE, 0, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.xlabelLE = QtWidgets.QLineEdit(self.centralwidget)
        self.xlabelLE.setObjectName("xlabelLE")
        self.gridLayout.addWidget(self.xlabelLE, 1, 1, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.ylabelLE = QtWidgets.QLineEdit(self.centralwidget)
        self.ylabelLE.setObjectName("ylabelLE")
        self.gridLayout.addWidget(self.ylabelLE, 2, 1, 1, 2)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.gridLayout.addWidget(self.tableWidget, 3, 0, 3, 4)
        self.upBtn = QtWidgets.QPushButton(self.centralwidget)
        self.upBtn.setObjectName("upBtn")
        self.gridLayout.addWidget(self.upBtn, 3, 4, 1, 1)
        self.downBtn = QtWidgets.QPushButton(self.centralwidget)
        self.downBtn.setObjectName("downBtn")
        self.gridLayout.addWidget(self.downBtn, 4, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 215, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 5, 4, 1, 1)
        self.addBtn = QtWidgets.QPushButton(self.centralwidget)
        self.addBtn.setObjectName("addBtn")
        self.gridLayout.addWidget(self.addBtn, 6, 0, 1, 1)
        self.gridCB = QtWidgets.QCheckBox(self.centralwidget)
        self.gridCB.setChecked(True)
        self.gridCB.setObjectName("gridCB")
        self.gridLayout.addWidget(self.gridCB, 0, 4, 1, 1)
        self.legendCB = QtWidgets.QCheckBox(self.centralwidget)
        self.legendCB.setChecked(True)
        self.legendCB.setObjectName("legendCB")
        self.gridLayout.addWidget(self.legendCB, 1, 4, 1, 1)
        self.removeBtn = QtWidgets.QPushButton(self.centralwidget)
        self.removeBtn.setObjectName("removeBtn")
        self.gridLayout.addWidget(self.removeBtn, 6, 1, 1, 1)
        self.plotBtn = QtWidgets.QPushButton(self.centralwidget)
        self.plotBtn.setObjectName("plotBtn")
        self.gridLayout.addWidget(self.plotBtn, 6, 2, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 405, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionDevelopment_Tool = QtWidgets.QAction(MainWindow)
        self.actionDevelopment_Tool.setObjectName("actionDevelopment_Tool")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionDevelopment_Tool)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CSV Ploter"))
        self.label.setText(_translate("MainWindow", "Title"))
        self.titleLE.setPlaceholderText(_translate("MainWindow", "Y Vs. X"))
        self.label_2.setText(_translate("MainWindow", "x-label"))
        self.xlabelLE.setPlaceholderText(_translate("MainWindow", "x (s)"))
        self.label_3.setText(_translate("MainWindow", "y-label"))
        self.ylabelLE.setPlaceholderText(_translate("MainWindow", "y (m)"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "File"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Label"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Color"))
        self.upBtn.setText(_translate("MainWindow", "^"))
        self.downBtn.setText(_translate("MainWindow", "v"))
        self.addBtn.setText(_translate("MainWindow", "Add"))
        self.gridCB.setText(_translate("MainWindow", "Grid"))
        self.legendCB.setText(_translate("MainWindow", "Legend"))
        self.removeBtn.setText(_translate("MainWindow", "Remove"))
        self.plotBtn.setText(_translate("MainWindow", "Plot"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionOpen.setText(_translate("MainWindow", "Open..."))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as..."))
        self.actionSave_as.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionAbout.setText(_translate("MainWindow", "About..."))
        self.actionAbout.setShortcut(_translate("MainWindow", "F1"))
        self.actionDevelopment_Tool.setText(_translate("MainWindow", "Development Tool"))
        self.actionDevelopment_Tool.setShortcut(_translate("MainWindow", "F10"))

